version: '3'

services:
  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/status"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
